NumPy Assignment - Complete Solution

Part 1: Creating NumPy Arrays

1. Using Built-in Methods

Import NumPy Library

In [2]:
import numpy as np

Create Array from 0 to 20 with step 2

In [3]:
print("Array from 0 to 20 with step 2:", np.arange(0, 21, 2))

Array from 0 to 20 with step 2: [ 0  2  4  6  8 10 12 14 16 18 20]


Create 3x3 Identity Matrix

In [4]:
print("3x3 identity matrix:")
print(np.eye(3))

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create 4x4 Array of Ones

In [5]:
print("4x4 array filled with ones:")
print(np.ones((4, 4)))

4x4 array filled with ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create 10 Equally Spaced Numbers

In [ ]:
print("10 equally spaced numbers between 5 and 50:", np.linspace(5, 50, 10))

2. Creating Arrays from Lists

Convert Python List to NumPy Array

In [ ]:
my_list = [10, 20, 30, 40, 50]
print("NumPy array from list:", np.array(my_list))

Generate 3x3 Random Matrices

In [ ]:
print("3x3 matrix using rand():")
print(np.random.rand(3, 3))

In [ ]:
print("3x3 matrix using randn():")
print(np.random.randn(3, 3))

In [ ]:
print("3x3 matrix using randint():")
print(np.random.randint(0, 10, (3, 3)))

3. Array Attributes

In [ ]:
ones_matrix = np.ones((4, 4))
print("Shape of ones_matrix:", ones_matrix.shape)
print("Size of ones_matrix:", ones_matrix.size)
print("Data type of ones_matrix:", ones_matrix.dtype)

Part 2: Indexing and Selection

1. Basic Indexing and Selection

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30])
print("Original array:", arr)
print("First element:", arr[0])
print("Last three elements:", arr[-3:])
print("Elements at index 1 to 4:", arr[1:5])

2. Slicing and Views

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print("3x3 matrix:")
print(matrix)
print("Second row:", matrix[1])
print("First two columns:")
print(matrix[:, :2])
print("2x2 sub-matrix:")
print(matrix[:2, :2])

3. Broadcasting

In [6]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix:")
print(test_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
result1 = test_matrix + 10
print("After adding 10:")
print(result1)

After adding 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
test_matrix[:, 0] = test_matrix[:, 0] * 2
print("After multiplying first column by 2:")
print(test_matrix)

4. Copying Arrays

In [8]:
original = np.array([1, 2, 3, 4, 5])
shallow_copy = original
shallow_copy[0] = 99
print("After modifying shallow copy:")
print("Original:", original)
print("Shallow copy:", shallow_copy)

After modifying shallow copy:
Original: [99  2  3  4  5]
Shallow copy: [99  2  3  4  5]


In [9]:
original = np.array([1, 2, 3, 4, 5])
deep_copy = original.copy()
deep_copy[0] = 99
print("After modifying deep copy:")
print("Original:", original)
print("Deep copy:", deep_copy)

After modifying deep copy:
Original: [1 2 3 4 5]
Deep copy: [99  2  3  4  5]


5. Fancy Indexing

In [ ]:
arr2 = np.arange(10, 101, 10)
print("Array:", arr2)
selected = arr2[[0, 3, 5]]
print("Elements at indices [0, 3, 5]:", selected)

Part 3: NumPy Operations

1. Mathematical Functions

In [ ]:
math_array = np.array([3, 7, 2, 9, 12, 5, 10])
print("Array:", math_array)
print("Maximum value:", np.max(math_array))
print("Minimum value:", np.min(math_array))
print("Index of maximum:", np.argmax(math_array))
print("Index of minimum:", np.argmin(math_array))

2. Universal Array Functions

In [10]:
func_array = np.array([1, 2, 3, 4, 5])
print("Original array:", func_array)
print("Square root:", np.sqrt(func_array))
print("Exponential:", np.exp(func_array))
print("Sine:", np.sin(func_array))
print("Natural logarithm:", np.log(func_array))

Original array: [1 2 3 4 5]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
